version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - tanulo-network
    restart: always
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    networks:
      tanulo-network:
        aliases:
          - postgresql.db
    volumes:
      - postgres:/var/lib/postgresql/tanulo-data
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo-volume:/data/db
    networks:
      tanulo-network:
        aliases:
          - mongodb
volumes:
  postgres:
  mongo-volume:
networks:
  tanulo-network:
