version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - tanulo-network
    restart: always
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    networks:
      tanulo-network:
        aliases:
          - postgresql.db
    volumes:
      - postgres:/var/lib/postgresql/tanulo-data
volumes:
  postgres:
networks:
  tanulo-network:
