version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - tanulo-network
    restart: always
  db:
    image: postgres:12
    restart: always
    env_file:
      - .env
    networks:
      - tanulo-network
    volumes:
      - tanulo_db_folder:/var/lib/postgresql/tanulo-data
volumes:
  tanulo_db_folder:
networks:
  tanulo-network:
